#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
python manage.py migrate

#python manage.py loaddata my_tourist/users/fixtures/user.yaml
#
#python manage.py loaddata my_tourist/map/fixtures/region.yaml
#python manage.py loaddata my_tourist/map/fixtures/region_credentials.yaml
#python manage.py loaddata my_tourist/map/fixtures/region_responsible.yaml
#python manage.py loaddata my_tourist/map/fixtures/salary.yaml
#python manage.py loaddata my_tourist/map/fixtures/heat_map.yaml
#python manage.py loaddata my_tourist/map/fixtures/audience.yaml
#
#python manage.py loaddata my_tourist/conf/fixtures/app_settings.yaml

python manage.py runserver_plus 0.0.0.0:8000
