# Generated by Django 3.1.4 on 2020-12-28 07:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tourism_type', models.CharField(choices=[('travel', 'Путешествия'), ('excursion', 'Экскурсии'), ('spa', 'SPA и оздоровление'), ('extreme', 'Активный отдых и экстрим'), ('outdoor', 'Развлечения и общение')], default='travel', max_length=10, verbose_name='Вид туризма')),
                ('phrases', models.TextField(help_text='Введите поисковые фразы отделив их переводом строки', verbose_name='Фразы для построения тепловой карты')),
                ('global_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_global_codes', to='map.region', verbose_name='Регион портала')),
            ],
            options={
                'verbose_name': 'Настройки тепловой карты',
                'verbose_name_plural': 'Настройки тепловой карты',
                'unique_together': {('tourism_type', 'global_code')},
            },
        ),
    ]
