# Generated by Django 4.0.3 on 2022-11-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regioncredentials',
            name='yandex_answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ в Яндекс'),
        ),
    ]
