#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate

# Data loading
if [ -e my_tourist/map/fixtures/heatmap.yaml ]; then
    python manage.py loaddata my_tourist/map/fixtures/heatmap.yaml
fi

# (only for the first build)
#
# python manage.py loaddata my_tourist/users/fixtures/user.yaml
#
# python manage.py loaddata my_tourist/map/fixtures/region.yaml
# python manage.py loaddata my_tourist/map/fixtures/region_credentials.yaml
# python manage.py loaddata my_tourist/map/fixtures/region_responsible.yaml
# python manage.py loaddata my_tourist/map/fixtures/salary.yaml
# python manage.py loaddata my_tourist/map/fixtures/heat_map.yaml
# python manage.py loaddata my_tourist/map/fixtures/audience.yaml
#
# python manage.py loaddata my_tourist/conf/fixtures/app_settings.yaml

# python manage.py ipgeobase_update

python /app/manage.py collectstatic --noinput

compress_enabled() {
python << END
import sys

from environ import Env

env = Env(COMPRESS_ENABLED=(bool, True))
if env('COMPRESS_ENABLED'):
    sys.exit(0)
else:
    sys.exit(1)

END
}

if compress_enabled; then
  # NOTE this command will fail if django-compressor is disabled
  python /app/manage.py compress
fi

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
